name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macOS 13+ required for ScreenCaptureKit
        os: [macos-13, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          # Build for Python 3.9 through 3.13
          CIBW_BUILD: cp39-* cp310-* cp311-* cp312-* cp313-*
          # Skip 32-bit builds and all Linux builds (Linux not supported)
          CIBW_SKIP: "*-win32 *-manylinux* *-musllinux_*"
          # macOS: Only build for macOS 13.0+, universal2 and arm64
          CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
          CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=13.0
          # Windows: Build for amd64 only
          CIBW_ARCHS_WINDOWS: "AMD64"
          # Install test dependencies
          CIBW_TEST_REQUIRES: pytest
          # Run tests (skip on macOS due to permission requirements)
          CIBW_TEST_COMMAND_WINDOWS: pytest {project}/tests
          CIBW_TEST_SKIP: "*-macosx_*"
          # Repair wheel command for macOS
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
            delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

